- hosts: all
  become: true
  become_user: root
  tasks:

  vars_files:
    - vars.yml

  - name: Install Git
    apt:
      name: git
      state: present

  - name: Clone repository
    git:
      repo: {{git_repo_url}}
      dest: {{work_location}}
      version: {{ git_branch }}


  - name: Download file from Google Drive
    command: gdown {{dataset_link}}
    args:
      creates: {{source_Extract}}

  - name: Extract file
    unarchive:
      src: {{source_Extract}}
      dest: {{work_location}}


# ssh -i ~/.ssh/MainVm_key.pem azureuser@read-it.francecentral.cloudapp.azure.com
# ansible-playbook -i hosts ./StartVm.yml --private-key=~/.ssh/Read-it.pem
